//user
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT = "USER_LOGOUT";

//population
export const LIST_POPULATIONS_REQUEST = "LIST_POPULATIONS_REQUEST";
export const LIST_POPULATIONS_SUCCESS = "LIST_POPULATIONS_SUCCESS";
export const LIST_POPULATIONS_FAILED = "LIST_POPULATIONS_FAILED";

export const LIST_POPULATIONS_MIDDLE_REQUEST =
  "LIST_POPULATIONS_MIDDLE_REQUEST";
export const LIST_POPULATIONS_MIDDLE_SUCCESS =
  "LIST_POPULATIONS_MIDDLE_SUCCESS";
export const LIST_POPULATIONS_MIDDLE_FAILED = "LIST_POPULATIONS_MIDDLE_FAILED";
//population middle
export const ADD_POPULATIONS_MIDDLE_REQUEST = "ADD_POPULATIONS_MIDDLE_REQUEST";
export const ADD_POPULATIONS_MIDDLE_SUCCESS = "ADD_POPULATIONS_MIDDLE_SUCCESS";
export const ADD_POPULATIONS_MIDDLE_FAILED = "ADD_POPULATIONS_MIDDLE_FAILED";
//age

export const LIST_POPULATIONS_AGE_REQUEST = "LIST_POPULATIONS_AGE_REQUEST";
export const LIST_POPULATIONS_AGE_SUCCESS = "LIST_POPULATIONS_AGE_SUCCESS";
export const LIST_POPULATIONS_AGE_FAILED = "LIST_POPULATIONS_AGE_FAILED";

export const ADD_POPULATIONS_AGE_REQUEST = "ADD_POPULATIONS_AGE_REQUEST";
export const ADD_POPULATIONS_AGE_SUCCESS = "ADD_POPULATIONS_AGE_SUCCESS";
export const ADD_POPULATIONS_AGE_FAILED = "ADD_POPULATIONS_AGE_FAILED";

export const LIST_POPULATIONS_TOTAL_REQUEST = "LIST_POPULATIONS_TOTAL_REQUEST";
export const LIST_POPULATIONS_TOTAL_SUCCESS = "LIST_POPULATIONS_TOTAL_SUCCESS";
export const LIST_POPULATIONS_TOTAL_FAILED = "LIST_POPULATIONS_TOTAL_FAILED";

export const LIST_TOTAL_AGE_REQUEST = "LIST_TOTAL_AGE_REQUEST";
export const LIST_TOTAL_AGE_SUCCESS = "LIST_TOTAL_AGE_SUCCESS";
export const LIST_TOTAL_AGE_FAILED = "LIST_TOTAL_AGE_FAILED";

//
export const LIST_POPULATIONS_FAMILY_REQUEST =
  "LIST_POPULATIONS_FAMILY_REQUEST";
export const LIST_POPULATIONS_FAMILY_SUCCESS =
  "LIST_POPULATIONS_FAMILY_SUCCESS";
export const LIST_POPULATIONS_FAMILY_FAILED = "LIST_POPULATIONS_FAMILY_FAILED";
//edu/students
export const LIST_EDU_PRE_STU_REQUEST = "LIST_EDU_PRE_STU_REQUEST";
export const LIST_EDU_PRE_STU_SUCCESS = "LIST_EDU_PRE_STU_SUCCESS";
export const LIST_EDU_PRE_STU_FAILED = "LIST_EDU_PRE_STU_FAILED";

export const LIST_EDU_MID_PRE_STU_REQUEST = "LIST_EDU_MID_PRE_STU_REQUEST";
export const LIST_EDU_MID_PRE_STU_SUCCESS = "LIST_EDU_MID_PRE_STU_SUCCESS";
export const LIST_EDU_MID_PRE_STU_FAILED = "LIST_EDU_MID_PRE_STU_FAILED";

export const ADD_STUDENTS_REQUEST = "ADD_STUDENTS_REQUEST";
export const ADD_STUDENTS_SUCCESS = "ADD_STUDENTS_SUCCESS";
export const ADD_STUDENTS_FAILED = "ADD_STUDENTS_FAILED";

//edu/classes
export const LIST_EDU_CLASS_REQUEST = "LIST_EDU_CLASS_REQUEST";
export const LIST_EDU_CLASS_SUCCESS = "LIST_EDU_CLASS_SUCCESS";
export const LIST_EDU_CLASS_FAILED = "LIST_EDU_CLASS_FAILED";

export const LIST_EDU_MID_CLASS_REQUEST = "LIST_EDU_MID_CLASS_REQUEST";
export const LIST_EDU_MID_CLASS_SUCCESS = "LIST_EDU_MID_CLASS_SUCCESS";
export const LIST_EDU_MID_CLASS_FAILED = "LIST_EDU_MID_CLASS_FAILED";

export const ADD_CLASSES_REQUEST = "ADD_CLASSES_REQUEST";
export const ADD_CLASSES_SUCCESS = "ADD_CLASSES_SUCCESS";
export const ADD_CLASSES_FAILED = "ADD_CLASSES_FAILED";
//edu/schools
export const LIST_EDU_SCHOOL_REQUEST = "LIST_EDU_SCHOOL_REQUEST";
export const LIST_EDU_SCHOOL_SUCCESS = "LIST_EDU_SCHOOL_SUCCESS";
export const LIST_EDU_SCHOOL_FAILED = "LIST_EDU_SCHOOL_FAILED";

export const LIST_EDU_MID_SCHOOL_REQUEST = "LIST_EDU_MID_SCHOOL_REQUEST";
export const LIST_EDU_MID_SCHOOL_SUCCESS = "LIST_EDU_MID_SCHOOL_SUCCESS";
export const LIST_EDU_MID_SCHOOL_FAILED = "LIST_EDU_MID_SCHOOL_FAILED";

export const ADD_SCHOOLS_REQUEST = "ADD_SCHOOLS_REQUEST";
export const ADD_SCHOOLS_SUCCESS = "ADD_SCHOOLS_SUCCESS";
export const ADD_SCHOOLS_FAILED = "ADD_SCHOOLS_FAILED";

//edu/azhar
export const LIST_EDU_AZHAR_REQUEST = "LIST_EDU_AZHAR_REQUEST";
export const LIST_EDU_AZHAR_SUCCESS = "LIST_EDU_AZHAR_SUCCESS";
export const LIST_EDU_AZHAR_FAILED = "LIST_EDU_AZHAR_FAILED";

//edu/teacher
export const LIST_EDU_TEACHER_REQUEST = "LIST_EDU_TEACHER_REQUEST";
export const LIST_EDU_TEACHER_SUCCESS = "LIST_EDU_TEACHER_SUCCESS";
export const LIST_EDU_TEACHER_FAILED = "LIST_EDU_TEACHER_FAILED";

export const ADD_TEACHER_REQUEST = "ADD_TEACHER_REQUEST";
export const ADD_TEACHER_SUCCESS = "ADD_TEACHER_SUCCESS";
export const ADD_TEACHER_FAILED = "ADD_TEACHER_FAILED";

//edu/avg
export const LIST_EDU_AVG_REQUEST = "LIST_EDU_AVG_REQUEST";
export const LIST_EDU_AVG_SUCCESS = "LIST_EDU_AVG_SUCCESS";
export const LIST_EDU_AVG_FAILED = "LIST_EDU_AVG_FAILED";

//culture

//cinema
export const LIST_CINEMA_REQUEST = "LIST_CINEMA_REQUEST";
export const LIST_CINEMA_SUCCESS = "LIST_CINEMA_SUCCESS";
export const LIST_CINEMA_FAILED = "LIST_CINEMA_FAILED";

export const ADD_CINEMA_REQUEST = "ADD_CINEMA_REQUEST";
export const ADD_CINEMA_SUCCESS = "ADD_CINEMA_SUCCESS";
export const ADD_CINEMA_FAILED = "ADD_CINEMA_FAILED";

//theater
export const LIST_THEATER_REQUEST = "LIST_THEATER_REQUEST";
export const LIST_THEATER_SUCCESS = "LIST_THEATER_SUCCESS";
export const LIST_THEATER_FAILED = "LIST_THEATER_FAILED";

export const ADD_THEATER_REQUEST = "ADD_THEATER_REQUEST";
export const ADD_THEATER_SUCCESS = "ADD_THEATER_SUCCESS";
export const ADD_THEATER_FAILED = "ADD_THEATER_FAILED";

//health
export const LIST_HEALTH_DEATH_REQUEST = "LIST_HEALTH_DEATH_REQUEST";
export const LIST_HEALTH_DEATH_SUCCESS = "LIST_HEALTH_DEATH_SUCCESS";
export const LIST_HEALTH_DEATH_FAILED = "LIST_HEALTH_DEATH_FAILED";

export const ADD_HEALTH_DEATH_REQUEST = "ADD_HEALTH_DEATH_REQUEST";
export const ADD_HEALTH_DEATH_SUCCESS = "ADD_HEALTH_DEATH_SUCCESS";
export const ADD_HEALTH_DEATH_FAILED = "ADD_HEALTH_DEATH_FAILED";
//international
export const LIST_INTERNATIONAL_REQUEST = "LIST_INTERNATIONAL_REQUEST";
export const LIST_INTERNATIONAL_SUCCESS = "LIST_INTERNATIONAL_SUCCESS";
export const LIST_INTERNATIONAL_FAILED = "LIST_INTERNATIONAL_FAILED";

export const LIST_INTERNATIONAL2_REQUEST = "LIST_INTERNATIONAL2_REQUEST";
export const LIST_INTERNATIONAL2_SUCCESS = "LIST_INTERNATIONAL2_SUCCESS";
export const LIST_INTERNATIONAL2_FAILED = "LIST_INTERNATIONAL2_FAILED";

export const LIST_INTERNATIONAL_DEMOGRAPHY_REQUEST =
  "LIST_INTERNATIONAL_DEMOGRAPHY_REQUEST";
export const LIST_INTERNATIONAL_DEMOGRAPHY_SUCCESS =
  "LIST_INTERNATIONAL_DEMOGRAPHY_SUCCESS";
export const LIST_INTERNATIONAL_DEMOGRAPHY_FAILED =
  "LIST_INTERNATIONAL_DEMOGRAPHY_FAILED";

export const LIST_INTERNATIONAL_GENDER_REQUEST =
  "LIST_INTERNATIONAL_GENDER_REQUEST";
export const LIST_INTERNATIONAL_GENDER_SUCCESS =
  "LIST_INTERNATIONAL_GENDER_SUCCESS";
export const LIST_INTERNATIONAL_GENDER_FAILED =
  "LIST_INTERNATIONAL_GENDER_FAILED";

export const LIST_INTERNATIONAL_ECONOMIC_REQUEST =
  "LIST_INTERNATIONAL_ECONOMIC_REQUEST";
export const LIST_INTERNATIONAL_ECONOMIC_SUCCESS =
  "LIST_INTERNATIONAL_ECONOMIC_SUCCESS";
export const LIST_INTERNATIONAL_ECONOMIC_FAILED =
  "LIST_INTERNATIONAL_ECONOMIC_FAILED";

export const LIST_INTERNATIONAL_EDUCATION_REQUEST =
  "LIST_INTERNATIONAL_EDUCATION_REQUEST";
export const LIST_INTERNATIONAL_EDUCATION_SUCCESS =
  "LIST_INTERNATIONAL_EDUCATION_SUCCESS";
export const LIST_INTERNATIONAL_EDUCATION_FAILED =
  "LIST_INTERNATIONAL_EDUCATION_FAILED";

export const LIST_INTERNATIONAL_DHS_WOMAN_REQUEST =
  "LIST_INTERNATIONAL_DHS_WOMAN_REQUEST";
export const LIST_INTERNATIONAL_DHS_WOMAN_SUCCESS =
  "LIST_INTERNATIONAL_DHS_WOMAN_SUCCESS";
export const LIST_INTERNATIONAL_DHS_WOMAN_FAILED =
  "LIST_INTERNATIONAL_DHS_WOMAN_FAILED";

export const LIST_INTERNATIONAL_DHS_CHILD_REQUEST =
  "LIST_INTERNATIONAL_DHS_CHILD_REQUEST";
export const LIST_INTERNATIONAL_DHS_CHILD_SUCCESS =
  "LIST_INTERNATIONAL_DHS_CHILD_SUCCESS";
export const LIST_INTERNATIONAL_DHS_CHILD_FAILED =
  "LIST_INTERNATIONAL_DHS_CHILD_FAILED";

export const LIST_INTERNATIONAL_DHS_FGM_REQUEST =
  "LIST_INTERNATIONAL_DHS_FGM_REQUEST";
export const LIST_INTERNATIONAL_DHS_FGM_SUCCESS =
  "LIST_INTERNATIONAL_DHS_FGM_SUCCESS";
export const LIST_INTERNATIONAL_DHS_FGM_FAILED =
  "LIST_INTERNATIONAL_DHS_FGM_FAILED";

export const LIST_INTERNATIONAL_DHS_PHYSICAL_REQUEST =
  "LIST_INTERNATIONAL_DHS_PHYSICAL_REQUEST";
export const LIST_INTERNATIONAL_DHS_PHYSICAL_SUCCESS =
  "LIST_INTERNATIONAL_DHS_PHYSICAL_SUCCESS";
export const LIST_INTERNATIONAL_DHS_PHYSICAL_FAILED =
  "LIST_INTERNATIONAL_DHS_PHYSICAL_FAILED";

export const ADD_INTERNATIONAL_REQUEST = "ADD_INTERNATIONAL_REQUEST";
export const ADD_INTERNATIONAL_SUCCESS = "ADD_INTERNATIONAL_SUCCESS";
export const ADD_INTERNATIONAL_FAILED = "ADD_INTERNATIONAL_FAILED";

export const ADD_INTERNATIONAL_DEMOGRAPHY_REQUEST =
  "ADD_INTERNATIONAL_DEMOGRAPHY_REQUEST";
export const ADD_INTERNATIONAL_DEMOGRAPHY_SUCCESS =
  "ADD_INTERNATIONAL_DEMOGRAPHY_SUCCESS";
export const ADD_INTERNATIONAL_DEMOGRAPHY_FAILED =
  "ADD_INTERNATIONAL_DEMOGRAPHY_FAILED";

export const ADD_INTERNATIONAL_GENDER_REQUEST =
  "ADD_INTERNATIONAL_GENDER_REQUEST";
export const ADD_INTERNATIONAL_GENDER_SUCCESS =
  "ADD_INTERNATIONAL_GENDER_SUCCESS";
export const ADD_INTERNATIONAL_GENDER_FAILED =
  "ADD_INTERNATIONAL_GENDER_FAILED";

export const ADD_INTERNATIONAL_ECONOMIC_REQUEST =
  "ADD_INTERNATIONAL_ECONOMIC_REQUEST";
export const ADD_INTERNATIONAL_ECONOMIC_SUCCESS =
  "ADD_INTERNATIONAL_ECONOMIC_SUCCESS";
export const ADD_INTERNATIONAL_ECONOMIC_FAILED =
  "ADD_INTERNATIONAL_ECONOMIC_FAILED";

export const ADD_INTERNATIONAL_EDUCATION_REQUEST =
  "ADD_INTERNATIONAL_EDUCATION_REQUEST";
export const ADD_INTERNATIONAL_EDUCATION_SUCCESS =
  "ADD_INTERNATIONAL_EDUCATION_SUCCESS";
export const ADD_INTERNATIONAL_EDUCATION_FAILED =
  "ADD_INTERNATIONAL_EDUCATION_FAILED";

export const ADD_INTERNATIONAL_DHS_WOMAN_REQUEST =
  "ADD_INTERNATIONAL_DHS_WOMAN_REQUEST";
export const ADD_INTERNATIONAL_DHS_WOMAN_SUCCESS =
  "ADD_INTERNATIONAL_DHS_WOMAN_SUCCESS";
export const ADD_INTERNATIONAL_DHS_WOMAN_FAILED =
  "ADD_INTERNATIONAL_DHS_WOMAN_FAILED";

export const ADD_INTERNATIONAL_DHS_CHILD_REQUEST =
  "ADD_INTERNATIONAL_DHS_CHILD_REQUEST";
export const ADD_INTERNATIONAL_DHS_CHILD_SUCCESS =
  "ADD_INTERNATIONAL_DHS_CHILD_SUCCESS";
export const ADD_INTERNATIONAL_DHS_CHILD_FAILED =
  "ADD_INTERNATIONAL_DHS_CHILD_FAILED";

export const ADD_INTERNATIONAL_DHS_FGM_REQUEST =
  "ADD_INTERNATIONAL_DHS_FGM_REQUEST";
export const ADD_INTERNATIONAL_DHS_FGM_SUCCESS =
  "ADD_INTERNATIONAL_DHS_FGM_SUCCESS";
export const ADD_INTERNATIONAL_DHS_FGM_FAILED =
  "ADD_INTERNATIONAL_DHS_FGM_FAILED";

export const ADD_INTERNATIONAL_DHS_PHYSICAL_REQUEST =
  "ADD_INTERNATIONAL_DHS_PHYSICAL_REQUEST";
export const ADD_INTERNATIONAL_DHS_PHYSICAL_SUCCESS =
  "ADD_INTERNATIONAL_DHS_PHYSICAL_SUCCESS";
export const ADD_INTERNATIONAL_DHS_PHYSICAL_FAILED =
  "ADD_INTERNATIONAL_DHS_PHYSICAL_FAILED";

export const ADD_WORLD_REQUEST = "ADD_WORLD_REQUEST";
export const ADD_WORLD_SUCCESS = "ADD_WORLD_SUCCESS";
export const ADD_WORLD_FAILED = "ADD_WORLD_FAILED";
//sports
export const LIST_SPORTS_CLUBS_REQUEST = "LIST_SPORTS_CLUBS_REQUEST";
export const LIST_SPORTS_CLUBS_SUCCESS = "LIST_SPORTS_CLUBS_SUCCESS";
export const LIST_SPORTS_CLUBS_FAILED = "LIST_SPORTS_CLUBS_FAILED";

export const ADD_SPORTS_CLUBS_REQUEST = "ADD_SPORTS_CLUBS_REQUEST";
export const ADD_SPORTS_CLUBS_SUCCESS = "ADD_SPORTS_CLUBS_SUCCESS";
export const ADD_SPORTS_CLUBS_FAILED = "ADD_SPORTS_CLUBS_FAILED";

export const LIST_SPORTS_COUNCIL_REQUEST = "LIST_SPORTS_COUNCIL_REQUEST";
export const LIST_SPORTS_COUNCIL_SUCCESS = "LIST_SPORTS_COUNCIL_SUCCESS";
export const LIST_SPORTS_COUNCIL_FAILED = "LIST_SPORTS_COUNCIL_FAILED";

export const ADD_SPORTS_COUNCIL_REQUEST = "ADD_SPORTS_COUNCIL_REQUEST";
export const ADD_SPORTS_COUNCIL_SUCCESS = "ADD_SPORTS_COUNCIL_SUCCESS";
export const ADD_SPORTS_COUNCIL_FAILED = "ADD_SPORTS_COUNCIL_FAILED";
//add data azhar
export const ADD_AZHAR_REQUEST = "ADD_AZHAR_REQUEST";
export const ADD_AZHAR_SUCCESS = "ADD_AZHAR_SUCCESS";
export const ADD_AZHAR_FAILED = "ADD_AZHAR_FAILED";
//info
export const LIST_CROWING_RATE_REQUEST = "LIST_CROWING_RATE_REQUEST";
export const LIST_CROWING_RATE_SUCCESS = "LIST_CROWING_RATE_SUCCESS";
export const LIST_CROWING_RATE_FAILED = "LIST_CROWING_RATE_FAILED";

export const LIST_SUPPORT_RATE_REQUEST = "LIST_SUPPORT_RATE_REQUEST";
export const LIST_SUPPORT_RATE_SUCCESS = "LIST_SUPPORT_RATE_SUCCESS";
export const LIST_SUPPORT_RATE_FAILED = "LIST_SUPPORT_RATE_FAILED";

export const LIST_AREA_RATE_REQUEST = "LIST_AREA_RATE_REQUEST";
export const LIST_AREA_RATE_SUCCESS = "LIST_AREA_RATE_SUCCESS";
export const LIST_AREA_RATE_FAILED = "LIST_AREA_RATE_FAILED";

export const LIST_INC_RATE_REQUEST = "LIST_INC_RATE_REQUEST";
export const LIST_INC_RATE_SUCCESS = "LIST_INC_RATE_SUCCESS";
export const LIST_INC_RATE_FAILED = "LIST_INC_RATE_FAILED";

export const LIST_IND_RATE_REQUEST = "LIST_IND_RATE_REQUEST";
export const LIST_IND_RATE_SUCCESS = "LIST_IND_RATE_SUCCESS";
export const LIST_IND_RATE_FAILED = "LIST_IND_RATE_FAILED";
//inds rate
export const LIST_INDS_AREA_RATE_REQUEST = "LIST_IND_AREA_RATE_REQUEST";
export const LIST_INDS_AREA_RATE_SUCCESS = "LIST_IND_AREA_RATE_SUCCESS";
export const LIST_INDS_AREA_RATE_FAILED = "LIST_IND_AREA_RATE_FAILED";
